pvparena: #тип арены.
  coordslobby: #Позиция лобби ожидания куда будет телепортировать игроков на ожидания боя, после смерти и после выиграша боя.
    x: 79
    y: 64
    z: 135
  world: eventworld #мир в котором будет турнир.
  timestart: 30
  coordsPlayer1: #позиция арены, игрока которого телепорнет на арену под номер 1.
    x: 75
    y: 64
    z: 135
  coordsPlayer2: #позиция арены, игрока которого телепорнет на арену под номер 2.
    x: 84
    y: 64
    z: 135