pvparena: #тип арены.
  coordslobby: #Позиция лобби ожидания куда будет телепортировать игроков на ожидания боя, после смерти и после выиграша боя.
    x: 79
    y: 64
    z: 135
  world: world_default_arena #мир в котором будет турнир.
  timestart: 30
  coordsPlayer1: #позиция арены, игрока которого телепорнет на арену под номер 1.
    x: 75
    y: 64
    z: 135
  coordsPlayer2: #позиция арены, игрока которого телепорнет на арену под номер 2.
    x: 84
    y: 64
    z: 135
  minplayer: 2 #Лимит минимальное количество игроков для старта ивента.
  maxplayer: 150 #Лимит максимальных игроков которые могут зайти на арену.